version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=D3345123Galsjd
      - POSTGRES_DB=kubex
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - main

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASS: D3345123Galsjd
      DB_NAME: kubex
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - main
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    networks:
      - main
volumes:
  db:
networks:
  main:
    name: main-network
